"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let fullName = "Baye Brian";
let age = 20;
let Occupation = "Student";
let School = "COLTECH";
let Department = "Computer Engineering";
let Level = 400;
let isFrontEndDeveloper = true;
let FavouriteLanguage = "English Language";
console.log(`Name: ${fullName}`);
console.log(`Age: ${age}`);
console.log(`School: ${School}`);
console.log(`Occupation: ${Occupation}`);
console.log(`Department: ${Department}`);
console.log(`Level: ${Level}`);
console.log(`Language: ${FavouriteLanguage}`);
console.log(`Frontend Developer: ${isFrontEndDeveloper}`);
let productName = "Keyboard";
const Price = 50;
let Quantity = 3;
let inStock = 10;
let Category = "Tech";
const totalPrice = Price * Quantity;
const QuantityAvailable = inStock - Quantity;
console.log(`Product Name: ${productName}`);
console.log(`Price: ${Price}`);
console.log(`Ordered Qty: ${Quantity}`);
console.log(`Initial Available Qty: ${inStock}`);
console.log(`Total: ${totalPrice}`);
console.log(`Final Available Qty: ${QuantityAvailable}`);
//# sourceMappingURL=index.js.map